version: "3.5"
services:
    docker_workshop:
        image: workshopregistry.azurecr.io/dockerworkshopapp:v2.2.6
        container_name: docker-workshop
        deploy:
            replicas: 1
            resources:
                limits:
                    cpus: "0.25"
                    memory: "50M"
            restart_policy:
                condition: "on-failure"
        ports:
            - "9008:7005"
        networks:
            - default

    another_docker_workshop:
        image: workshopregistry.azurecr.io/anotherdockerworkshopapp:v2.1.1
        container_name: another-docker-workshop
        deploy:
            replicas: 1
            resources:
                limits:
                    cpus: "0.25"
                    memory: "50M"
            restart_policy:
                condition: "on-failure"
        expose:
            - "7007"            
        networks:
            - default
networks:
    default:
        name: workshopdockernetwork
